### ISSUE TITLE
Zabbix 6.4 support

### ISSUE THREAD

**Issue by nextOver** [gr8b/zabbix-module-xgeomap#2]
Is possible enable on zabbix 6.4?

Is it possible to disable grouping of hosts in the map?

**Comment by gr8b** [comment]
> Is possible enable on zabbix 6.4?

In version 6.4, widgets were moved to independent modules, so I think it's easier to create a new one from scratch, using the code of the geomap widget from version 6.4 as a basis.

> Is it possible to disable grouping of hosts in the map?

Yes, add "`disableClusteringAtZoom: true`" to `markerClusterGroup` initialization object in `ui/widgets/geomap/assets/js/class.widget.js` to disable grouping. Also you can define radius in pixels with "`maxClusterRadius`", more options you can find on [leaflet.markerCluster](https://github.com/Leaflet/Leaflet.markercluster) repository page.

**Comment by nextOver** [comment]
> > É possível habilitar no zabbix 6.4?
> 
> Na versão 6.4, os widgets foram movidos para módulos independentes, então acho mais fácil criar um novo do zero, usando como base o código do widget geomap da versão 6.4.
> 
> > É possível desabilitar o agrupamento de hosts no mapa?
> 
> Sim, adicione " `disableClusteringAtZoom: true`" ao `markerClusterGroup`objeto de inicialização para `ui/widgets/geomap/assets/js/class.widget.js`desabilitar o agrupamento. Além disso, você pode definir o raio em pixels com " `maxClusterRadius`", mais opções você pode encontrar na página do repositório [leaflet.markerCluster .](https://github.com/Leaflet/Leaflet.markercluster)


thanks man, it worked perfectly. I will try to adapt the module to the new zabbix format :D
